// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $character_id_ from "./routes/character/[id].tsx";
import * as $favorites_favorites from "./routes/favorites/favorites.tsx";
import * as $index from "./routes/index.tsx";
import * as $CharactersContainer from "./islands/CharactersContainer.tsx";
import * as $SearchBar from "./islands/SearchBar.tsx";
import * as $StarButton from "./islands/StarButton.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/character/[id].tsx": $character_id_,
    "./routes/favorites/favorites.tsx": $favorites_favorites,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/CharactersContainer.tsx": $CharactersContainer,
    "./islands/SearchBar.tsx": $SearchBar,
    "./islands/StarButton.tsx": $StarButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
